### ISSUE TITLE
Search / Autocomplete not supported

### ISSUE THREAD

**Issue by marcantoine** [marcantoine/ra-data-graphql-prisma#1]
The dataProvider doesn't support search queries, so the AutocompleteInput from react admin is not working.

**Comment by 5achinJani** [comment]
hey @marcantoine  can you point us the code area where we can write the fix for this or at least a workaround?

**Comment by 5achinJani** [comment]
Also the `<SelectInput />` is not triggering the pagination so how do you deal with showing all the data. `perPage={100000}` is not an effective solution.
```jsx
        <ReferenceInput
          source="type.id"
          reference="ProductType"
          label="type"
          perPage={2}
        >
          <SelectInput optionText="name" resettable={true} />
          {/* <AutocompleteInput optionText="name" /> */}
        </ReferenceInput>
```

**Comment by 5achinJani** [comment]
@Vadorequest Have this occurred to you? this is a major blocker for us right now.

**Comment by Vadorequest** [comment]
I haven't reached this issue yet (didn't try AutocompleteInput)

If I understand correctly what @marcantoine has said, it's a limitation from the dataProvider, which is https://github.com/marmelab/react-admin/tree/master/packages/ra-data-graphql, forking this may be necessary... I was thinking about doing it to add TS support anyway.

If you want to play around with testing, I suggest you take a look at https://github.com/UnlyEd/next-right-now-admin/issues, which uses https://github.com/UnlyEd/ra-data-graphql-prisma

Honnestly, there are a lot of non-working things, I've listed only some of them on our https://github.com/UnlyEd/next-right-now-admin/issues but if you're interested we could work together to fix them all, I'm working against GraphCMS provider. See https://github.com/UnlyEd/next-right-now-admin/projects

**Comment by 5achinJani** [comment]
Hey @Vadorequest  that's great. yeah sure would love to contribute.

**Comment by Vadorequest** [comment]
@5achinJani Awesome! In that case I suggest you investigate why AutocompleteInput doesn't work and create an issue at https://github.com/UnlyEd/next-right-now-admin/issues with the result of your investigation. The first thing is to understand what's the cause of this.  

Also, tracking issues related to the data provider there: https://github.com/UnlyEd/ra-data-graphql-prisma/issues

**Comment by 5achinJani** [comment]
I've got the AutoComplete component working for now using:
`filterToQuery={searchText => ({ name_contains: searchText })}`
```jsx
        <ReferenceInput
          source="type.id"
          reference="ProductType"
          label="type"
          perPage={100}
          filterToQuery={searchText => ({ name_contains: searchText })}
        >
          <AutocompleteInput optionText="name" />
        </ReferenceInput>
```

```jsx
        <ReferenceArrayInput
          label="type"
          reference="ProductType"
          source="typeIds"
          perPage={100}
          filterToQuery={searchText => ({ name_contains: searchText })}
        >
          <AutocompleteArrayInput />
        </ReferenceArrayInput>
```

**Comment by Vadorequest** [comment]
Great! That's a nice workaround :)

**Comment by marcantoine** [comment]
That's amazing 5achinJani, and probably even better than customizing the dataProvider for that usecase.

Thank you !

**Comment by marcantoine** [comment]
After testing, I believe using filterToQuery is the way to use Autocomplete, I close this issue
