### ISSUE TITLE
Reference variable name is wrong

### ISSUE THREAD

**Issue by Vadorequest** [marcantoine/ra-data-graphql-prisma#20]
When using a reference variable, such as `theme.primaryColor`

```tsx
<ColorInput source="theme.primaryColor" label={'Color'} />
```

It generates the following:
![image](https://user-images.githubusercontent.com/3807458/76459863-408b1380-63dd-11ea-81e8-e0768e985052.png)

The issue is that `data: {theme: "#7bdcb5"}` is wrong, it should be `data: {theme:{primaryColor: "#7bdcb5"}}`.

Have you ever encountered this issue before @marcantoine ?

**Comment by marcantoine** [comment]
I'm not sure I understand the usecase.

Did you surrounded the ColorInput with a ReferenceInput ?
Here is an example of a similar usecase working on my side:

```html
<ReferenceInput source="product.id" reference="Product">
  <SelectInput optionText="name" />
</ReferenceInput>
```

So in your case, I guess it would be 
```html
<ReferenceInput source="theme.id" reference="Theme">
  <ColorInput optionText="primaryColor" label={'Color'} />
</ReferenceInput>
```

**Comment by Vadorequest** [comment]
No, I hadn't surrounded my ColorInput by a ReferenceInput.

When I do, I get `Uncaught TypeError: Cannot read property 'data' of undefined` from `getPossibleReferences` in `ra-core/esm/dataProvider` when displaying the form (while previously, the error happened when updating the form).

Using 
```tsx
<ReferenceInput source="theme.id" reference="Theme">
  <ColorInput source="primaryColor" label={'Color'} />
</ReferenceInput>
```

**Comment by marcantoine** [comment]
Is there a way in your schema to only query themes ? React-admin created dedicated queries for reference.

Also, react-Admin look up the different "ressources" declared in the App to match the reference ?
For example, I have a similar case and I had to add the Ressource in <Admin> 
```jsx
<Admin dataProvider={dataProvider}>
  <Resource name="Type" />
 </Admin>
```

**Comment by Vadorequest** [comment]
Nice tip! Indeed, creating a `<Resource name="Theme" />` fixed the issue, it's not crashing anymore.

I had created a dedicated query for Theme:

```tsx
import gql from 'graphql-tag';

// XXX https://www.apollographql.com/docs/react/advanced/fragments
export const theme = {
  themeFields: gql`
    fragment themeFields on Theme {
      id
      primaryColor
      logo {
        id
        url
        height
        width
        fileName
      }
    }
  `,
};

```

```tsx
import { GET_LIST, GET_ONE } from 'react-admin';
import { customer } from '../gql/fragments/customer';
import { product } from '../gql/fragments/product';
import { theme } from '../gql/fragments/theme';

export default {
  Customer: {
    [GET_LIST]: customer.customerFields,
    [GET_ONE]: customer.customerFields,
  },
  Product: {
    [GET_LIST]: product.productFields,
    [GET_ONE]: product.productFields,
  },
  Theme: {
    [GET_LIST]: theme.themeFields,
  },
};

```

---

But even this doesn't display the record properly. Here is what happens:

### Case 1
When I use `<ColorInput source="theme.primaryColor" label={'Color'} />`, the edit view displays properly AND the record is found:
![image](https://user-images.githubusercontent.com/3807458/76619295-cb2d5900-652a-11ea-99e8-aedbb289b1d1.png)

### Case 2
When  I use a `ReferenceInput` wrapper, the edit view displays but the record is not found and therefore doesn't load the color correctly:

```tsx
<ReferenceInput source="theme.id" reference="Theme">
  <ColorInput source="primaryColor" label={'Color'} />
</ReferenceInput>
```

![image](https://user-images.githubusercontent.com/3807458/76619458-3545fe00-652b-11ea-988c-58d062ec9df7.png)

Using a variant with `theme.primaryColor` instead of `primaryColor` doesn't change anything:

```tsx
<ReferenceInput source="theme.id" reference="Theme">
  <ColorInput source="theme.primaryColor" label={'Color'} />
</ReferenceInput>
```

**Comment by Vadorequest** [comment]
Okay, I think I'm trying to do something that's actually not possible.

The goal here was to make the value `primaryColor`, which is a linked value from a `Theme` model.

Each Customer has a `theme` property (instance of Theme model). I was trying to change the `customer.theme.primaryColor` value, but `ReferenceInput ` is only meant to change a reference, not the properties related to that reference.

How did you deal with that kind of needs @marcantoine ? Did you ever do that?

I think I need to update the prisma resolved to detect whether the changed property is the "id", if not then it should try to run a nested update, such as `{"where":{"id":"ck73s1dqm2ue30b98uepy9is3"},"data":{"theme":{"update": {"primaryColor": "blue"}}}}`.

And this wouldn't use the `ReferenceInput` at all.

**Comment by Vadorequest** [comment]
Fixed through https://github.com/UnlyEd/ra-data-graphql-prisma/pull/5
